/*This bit of code will summarize the data first in general then by drug class.*/
PROC MEANS DATA=MIS500.ALLYEARS mean sum;
PROC TABULATE DATA=MIS500.ALLYEARS;
	CLASS YEAR;
	VAR ALLCOSTS COUNTER;
	TABLE YEAR,
		  ALLCOSTS COUNTER;
PROC TABULATE DATA=MIS500.ALLYEARS;
	CLASS YEAR DRUGCLASS;
	VAR ALLCOSTS;
	TABLE DRUGCLASS,
          YEAR*ALLCOSTS;
PROC TABULATE DATA=MIS500.ALLYEARS;
	CLASS YEAR DRUGCLASS;
	VAR COUNTER;
	TABLE DRUGCLASS,
          YEAR*COUNTER;
RUN;
